.gitignore
contracts/router/PriceFeed.sol
lib/Exchange.js

Fixed a couple of typos.

---

test/nav.js
test/version.js

Hi. 
When I run the test according to your README instruction, I encountered the following 3 errors.
https://gist.github.com/makoto/8c117d741d9960a7116dcd2e4513f626
These changes should fix 2 of 3 errors. I don't think I can fix the last error as I cannot guess the correct behavior from the test and I also saw that other tests in the same test files are commented out.
Thanks.

Require contracts

---

contracts/Core.sol
contracts/CoreProtocol.sol
contracts/datafeeds/PriceFeed.sol
contracts/exchange/Exchange.sol
contracts/fees/PerformanceFee.sol
contracts/fees/PerformanceFeeProtocol.sol
contracts/participation/Subscribe.sol
contracts/riskmgmt/RiskMgmt.sol
contracts/riskmgmt/RiskMgmtProtocol.sol
contracts/riskmgmt/RiskMgmtV1.sol
migrations/4_deploy_riskmgmt.js
test/makeOrder.js
test/nav.js
utils/constants.js

Riskmgmtv1

---

package.json

Pretty simple actually. Publish with:
npm publish

Npm deploy

---

.travis.yml

Supporting [async](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) and [await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) functions

Node update to natively support async/await functionality

---

.solcover.js
.travis.yml
README.md
package-lock.json
package.json

- Adds coverage badge and tools
Note: coverage badge will only display coverage of master branch (will activate when we merge to Master)

Merge coverage into new-interface

---

.gitignore
contracts/Vault.sol
contracts/datafeeds/DataFeed.sol
contracts/dependencies/Logger.sol
contracts/governance/Version.sol
contracts/participation/Participation.sol
migrations/2_deploy_universe.js
migrations/6_deploy_gov.js
package.json
test/vault.js
utils/rpc.js

@retotrinkler 
in particular, I'm wondering if [this change](https://github.com/melonproject/protocol/compare/subscribe-rebase...add-vault-tests#diff-c29a373d5ba35ade4b1045a6318cfbe9L160) makes sense.

Add vault tests

---

contracts/Vault.sol
contracts/VaultInterface.sol
contracts/exchange/SimpleMarket.sol
package.json
test/exchange.js
test/vault-shares.js
test/vault-trading.js
test/vault.js

Adds tests for shares and trading (both of vault).

Add more tests

---

CHANGELOG.md
contracts/Vault.sol
contracts/datafeeds/DataFeed.sol
contracts/datafeeds/DataFeedInterface.sol
contracts/riskmgmt/RMMakeOrders.sol
contracts/riskmgmt/RiskMgmt.sol

Add: Initial version of RiskMgmt for make orders

Vault ref price

---

.travis.yml
contracts/Vault.sol
contracts/VaultInterface.sol
contracts/governance/Version.sol
contracts/riskmgmt/RMLiquidityProvider.sol
contracts/riskmgmt/RiskMgmt.sol
contracts/riskmgmt/RiskMgmtInterface.sol
package.json
test/version.js
truffle.js

- Change RiskMgmt function parameters
- Proof of Embezzlement
- closeOpenOrders
- shutDownVault

Internal accounting

---

contracts/Vault.sol
contracts/assets/AssetRegistrar.sol
contracts/datafeeds/DataFeed.sol
contracts/dependencies/BackupOwned.sol
contracts/governance/Governance.sol
contracts/governance/Version.sol
contracts/participation/Participation.sol
migrations/2_deploy_sphere.js
migrations/2_deploy_universe.js
migrations/3_deploy_modular_parts.js
migrations/4_deploy_governance.js
package.json
truffle.js

- Deployable (to Kovan) version of Protocol
- Some improvements in comments

Fix migrations

---

CHANGELOG.md
contracts/assets/AssetRegistrar.sol
contracts/dependencies/ERC20.sol

Implementing @holiman [initial partial report](https://gist.github.com/holiman/94e16c38b3899d515f03125be393abe7)

Martin audit

---

CHANGELOG.md
migrations/config/data_feed_info.js
migrations/config/exchange_info.js
package.json

- New addresses for Kovan deployment
- Changelog

New addresses

---

contracts/Fund.sol
contracts/version/Version.sol

- quantityHeldInCustodyOfExchange() function to fix accounting issue
- Require only one fund per manager in setupFund function call

Fix accounting

---

CHANGELOG.md
README.md
contracts/Fund.sol
contracts/FundInterface.sol
contracts/system/Governance.sol
contracts/version/Version.sol
contracts/version/VersionInterface.sol
src/Fund.sol
src/FundInterface.sol

- redeemUsingSlice -> redeemOwnedAssets
- Refactor: Governance contract
- Refactor: Version contract
- Update README

Governance

---

contracts/Fund.sol
contracts/version/Version.sol

- Added some natspecs comments to Version, Fund contract

Add natspecs comments

---

contracts/Fund.sol
contracts/Staked.sol
package.json

Fix return error

---

README.md

Simply fixing the paper url link.

Fix Paper URL

---

test/parity-genesis.config

- External libraries
- Parity devchain genesis settings

Add external libraries; Change devchain config

---

deployment/deploy-all.js
src/Fund.sol
src/datafeeds/DataFeed.sol
src/riskmgmt/RMMakeOrders.sol
test/before-tests.js
utils/password

- sellAsset param to getOrderPrice
- `password` to password file
- Documentation in PriceFeed
- Fix getReferencePrice
- Fix RMMakeOrders

Risk Mgmt percentage restriction

---

src/version/Version.sol
test/fund-shares.js

- Add fund names mapping to and pre condition s.t. fund names are unique
- #206

Add fund names mapping to and pre condition s.t. fund names are unique

---

src/Fund.sol

- `sharePrice` to `highWaterMark` in Calculations struct

Global high water mark implementation

---

PULL_REQUEST_TEMPLATE
deployment/deploy-all.js
package-lock.json
package.json

- Deployed Version
- PULL_REQUEST_TEMPLATE

Deploy 0.4.1

---

package-lock.json
src/Fund.sol

Account for open orders

---

deployment/data_feed_info.js
deployment/deploy-all.js
deployment/environment.config.js
deployment/token.info.js
package-lock.json
package.json
src/datafeeds/DataFeed.t.sol
src/version/Version.sol
tests/governance.js
tests/jasmine.json

- governance proposal, approval and triggering of new Version at deployment
- jasmine tests for governance of new Version (shutting down)
- test asset registration does not error
- TR datafeed address
- governance deployment parameters
- allow anyone to shut down a Fund deployed from a Version which has shut down
- bug destroying all blockchain data when starting devchain node
- GNT address (Golem token)
- stopped MLN from being registered twice

Merge before audit work

---

package-lock.json
package.json

- deploy protocol on melon chain
- release `0.5.2-melon.1`

0.5.2-melon.1

---

src/version/Version.sol
src/version/VersionInterface.sol

- Add fund name owned by concept

Add fund name owned by

---

src/FundInterface.sol
src/assets/Asset.sol
src/assets/AssetInterface.sol
src/assets/ERC223ReceivingContract.sol

- Shares as erc223 asset
- Fixes #309

Shares as erc223 compliant assets; Resolves #309

---

src/modules/ModuleRegistrar.sol

One vote per module

---

src/modules/ModuleRegistrar.sol
src/modules/ModuleRegistrar.t.sol

- Add commitHash in modules information struct
- Fixes #326

Add commitHash in modules information struct; Fixes #326

---

src/testing/ThrowToken.sol
tests/integration/fundTrading.js
tests/integration/redeemMaliciousAsset.js
utils/deploy/contracts.js

- ThrowToken.sol testing contract
- redeemMaliciousAsset.js

WIP: Beginning test for redemption with malicious asset

---

src/FundRanking.sol

Storage arrays moved to be local memory arrays in order to avoid 'view' function mutating the state.

Use memory arrays.

---

src/FundRanking.sol

Style adjusted.

---

README.md

- security@melonport.com email in readme

Add security email

---

CHANGELOG.md
src/Fund.sol
tests/integration/redeemMaliciousAsset.js
tests/unit/pricefeed/canonicalPriceFeed.js

- bug allowing emergencyRedeem to drain funds

Emergency redeem fix

---

src/Fund.sol
src/FundInterface.sol

Remove single asset redemption

---

src/Fund.sol
tests/integration/fundShares.js
tests/integration/fundTrading.js
tests/unit/compliance/onlyManager.js

- Small bug in executeRequest that fails investment execution
- Adjust integration tests based on single asset redemption

Adjust redemption tests

---

package.json
src/competitions/TestCompetition.sol
utils/deploy/contracts.js

- separated competition and testcompetition contracts

Separate test contract

---

src/Fund.sol
src/competitions/Competition.sol
src/competitions/TestCompetition.sol
tests/integration/competitionPayout.js
tests/unit/competitions/redeem.js
tests/unit/competitions/registration.js
utils/deploy/contracts.js

- Conditional deployment of competition contracts
- Naming of TestCompetition (constructor and contract name)
- Few failing competition tests

Minor test fix

---

src/Fund.sol

Switch comments FEE_RATE

---

src/Fund.sol
src/exchange/adapter/MatchingMarketAdapter.sol
src/testing/MaliciousToken.sol
tests/integration/0xTrading.js
tests/integration/competitionPayout.js
tests/integration/competitionRegistration.js
tests/integration/redeemMaliciousAsset.js
tests/unit/competitions/redeem.js
tests/unit/competitions/registration.js
tests/unit/pricefeed/canonicalPriceFeed.js
utils/deploy/contracts.js

- Get competition T & C in tests dynamically
- Test fixes / adjustments

Test fixes, dynamic way to get Competition T & C

---

.gitignore
package.json
src/contracts/exchanges/index.ts
src/contracts/exchanges/utils/getGenericExchangeInterfaceABI.ts
src/contracts/factory/transactions/deployFundFactory.ts
src/contracts/factory/transactions/setupFund.ts
src/contracts/fund/hub/calls/getSettings.ts
src/contracts/fund/hub/index.ts
src/contracts/fund/hub/utils/getHubContract.ts
src/contracts/fund/policies/index.ts
src/contracts/fund/policies/transactions/register.ts
src/contracts/fund/policies/utils/getPolicyManagerABI.ts
src/contracts/fund/policies/utils/getPolicyManagerContract.ts
src/contracts/fund/types.ts
src/utils/abi/getABI.ts
src/utils/abi/getFunctionSignature.ts
src/utils/deploySystem.test.ts
src/utils/deploySystem.ts
src/utils/environment/Environment.ts
src/utils/environment/initTestEnvironment.ts
src/utils/scratchpad.ts
src/utils/types.ts
yarn.lock

- getSettings (what was named getComponents in refactorDeploy.js)
- Function encoder functions
- Register policy (check the usage of enums)

Deploy system

---

src/contracts/dependencies/token/index.ts
src/contracts/dependencies/token/transactions/approve.test.ts
src/contracts/dependencies/token/transactions/approve.ts
src/utils/deploySystem.ts

Luong and me added some functions ...

Add Token.approve

---

src/contracts/factory/FundFactory.sol
src/contracts/factory/transactions/createComponents.ts
src/contracts/fund/accounting/Accounting.sol
src/contracts/fund/hub/Hub.sol
src/contracts/fund/participation/Participation.sol
src/contracts/fund/trading/Trading.sol
src/utils/deploySystem.ts
tests/integration/fundTrading.js

Small fixes in naming and slight refactor; things we found when Matt Di Ferrante worked with us.
Also added name back in to the fund.

Refactor survey fixes & add fund name

---

src/contracts/dependencies/token/index.ts
src/contracts/dependencies/token/transactions/increaseApproval.test.ts
src/contracts/dependencies/token/transactions/increaseApproval.ts
src/contracts/dependencies/token/transactions/transfer.test.ts
src/contracts/dependencies/token/transactions/transfer.ts
src/contracts/dependencies/token/transactions/transferFrom.test.ts
src/contracts/dependencies/token/transactions/transferFrom.ts

Implementing the remaining transactions of `StandardToken` contract applying `transactionFactory`

Walkthrough

---

src/contracts/fund/fees/FixedPerformanceFee.sol

- valuePerShare -> gavPerShare
- Bug in if condition to check gavPerShare > HWM

Fix bug in performance fee

---

src/Contracts.ts
src/contracts/fund/accounting/unit/accounting.test.ts
src/contracts/fund/fees/MockFee.sol
src/contracts/fund/fees/unit/feeManager.test.ts

Fee manager test

---

package.json

- Remove duplicated 0x.js version from package.json

0x-dependency

---

package.json
src/contracts/exchanges/EthfinexAdapter.sol
src/contracts/exchanges/KyberAdapter.sol
src/contracts/exchanges/MatchingMarketAdapter.sol
src/contracts/exchanges/ZeroExV2Adapter.sol
src/contracts/factory/FundFactory.sol
src/contracts/fund/accounting/Accounting.i.sol
src/contracts/fund/accounting/Accounting.sol
src/contracts/fund/accounting/unit/accounting.test.ts
src/contracts/fund/fees/FeeManager.sol
src/contracts/fund/fees/unit/feeManager.test.ts
src/contracts/fund/hub/Hub.sol
src/contracts/fund/hub/MockHub.sol
src/contracts/fund/hub/Spoke.sol
src/contracts/fund/participation/Participation.i.sol
src/contracts/fund/participation/Participation.sol
src/contracts/fund/participation/unit/investment.test.ts
src/contracts/fund/policies/Manager.sol
src/contracts/fund/policies/PolicyManager.sol
src/contracts/fund/policies/risk-management/unit/assetBlacklist.test.ts
src/contracts/fund/policies/risk-management/unit/assetWhitelist.test.ts
src/contracts/fund/policies/unit/mocks.test.ts
src/contracts/fund/trading/Trading.sol
src/contracts/fund/trading/unit/trading.test.ts
src/contracts/fund/trading/unit/tradingCallbacks.test.ts
src/utils/deployMockSystem.ts
yarn.lock

Adds some permissions where needed. Modified a few tests.
Fixes #569

Permissions

---

src/contracts/fund/accounting/calls/getQuoteToken.ts
src/contracts/fund/accounting/calls/performCalculations.ts
src/contracts/fund/hub/calls/getName.ts
src/index.ts
src/tests/integration/generalWalkthrough.test.ts

Add calls for accounting and hub

calls-accounting-hub

---

src/contracts/fund/fees/FixedManagementFee.sol

Clean up management fee code, remove gav variable

Clean up management fee code, remove gav variable

---

src/contracts/version/calls/getAmguPrice.ts

Fix getAmguPrice

---

src/contracts/fund/participation/transactions/requestInvestment.ts

Fix requestInvestment

---

src/Contracts.ts
src/contracts/factory/calls/getFundDetails.ts
src/contracts/factory/transactions/deployFundRanking.ts
src/index.ts
src/utils/deployMockSystem.ts
src/utils/deploySystem.ts

Depends on https://github.com/melonproject/protocol/pull/601

Deploy FundRanking and add getFundDetails call

---

README.md
package.json
src/contracts/engine/Engine.sol
src/contracts/exchanges/ExchangeAdapterInterface.sol
src/contracts/exchanges/KyberAdapter.sol
src/contracts/factory/Factory.sol
src/contracts/factory/FundFactory.sol
src/contracts/fund/accounting/Accounting.i.sol
src/contracts/fund/accounting/Accounting.sol
src/contracts/fund/fees/FeeManager.sol
src/contracts/fund/fees/FixedPerformanceFee.sol
src/contracts/fund/hub/Hub.sol
src/contracts/fund/participation/Participation.i.sol
src/contracts/fund/participation/Participation.sol
src/contracts/fund/participation/transactions/executeRequestFor.ts
src/contracts/fund/policies/AddressList.sol
src/contracts/fund/policies/PolicyManager.sol
src/contracts/fund/policies/compliance/UserBlacklist.sol
src/contracts/fund/policies/compliance/UserWhitelist.sol
src/contracts/fund/shares/Shares.sol
src/contracts/fund/trading/Trading.i.sol
src/contracts/fund/trading/Trading.sol
src/contracts/fund/vault/Vault.sol
src/contracts/fund/vault/transactions/createVaultInstance.ts
src/contracts/version/Registry.sol
src/contracts/version/Version.i.sol
src/contracts/version/Version.sol

- To get the conversation started

Documentation of the general principle & example

---

src/contracts/factory/transactions/setupFund.ts

Fix setup fund

---

bin/compile.js
bin/compile.ts
src/Contracts.ts
src/contracts/engine/transactions/sellAndBurnMln.test.ts
src/contracts/exchanges/thirdparty/0x/utils/createOrder.ts
src/contracts/exchanges/thirdparty/kyber/ExpectedRate.sol
src/contracts/exchanges/thirdparty/kyber/transactions/setBaseRate.ts
src/contracts/exchanges/transactions/deployKyberEnvironment.ts
src/contracts/prices/KyberPriceFeed.sol
src/contracts/prices/calls/getPrice.ts
src/contracts/prices/transactions/deployKyberPriceFeed.ts
src/contracts/prices/transactions/deployTestingPriceFeed.test.ts
src/contracts/prices/transactions/deployTestingPriceFeed.ts
src/contracts/prices/transactions/update.test.ts
src/tests/integration/kyber-price-feed.test.ts
src/utils/deploySystem.ts
src/utils/evm/getLatestBlock.ts
src/utils/solidity/prepareTransaction.ts
src/utils/solidity/transactionFactory.ts

Tests as example how to use Kyber as PriceFeed.

Kyber pricefeed

---

src/tests/utils/testLogger.ts

`yarn test; cat logs/test-latest.log | tail`

Log latest to file

---

src/contracts/exchanges/EthfinexAdapter.sol
src/contracts/exchanges/third-party/ethfinex/ExchangeEfx.sol
src/contracts/exchanges/third-party/ethfinex/WrapperRegistryEFX.sol
src/contracts/fund/hub/Hub.sol
src/contracts/version/Registry.sol

Wrapper registry

---

bin/melon.js
deployments/configs/kovan.json
deployments/kovan-default.json
package.json
src/contracts/dependencies/token/PreminedToken.sol
src/contracts/exchanges/transactions/deploy0xAdapter.ts
src/contracts/exchanges/transactions/deployKyberEnvironment.ts
src/contracts/exchanges/transactions/deployMatchingMarketAdapter.ts
src/contracts/fund/accounting/transactions/deployAccountingFactory.ts
src/contracts/fund/fees/transactions/deployFeeManagerFactory.ts
src/tests/integration/kyber-price-feed.test.ts
src/tests/utils/initTestEnvironment.ts
src/tests/utils/testLogger.ts
src/utils/environment/constructEnvironment.ts
src/utils/environment/initUnlockedEnvironment.ts
src/utils/solidity/deployContract.ts
yarn.lock

Kovan deploy

---

src/contracts/fund/hub/Spoke.sol
src/contracts/fund/participation/Participation.sol
src/contracts/fund/participation/calls/getRequest.ts
src/contracts/fund/participation/unit/investment.test.ts
src/contracts/prices/KyberPriceFeed.sol
src/utils/deployAndGetSystem.ts

Implement two-sided investment delay

---

package.json
src/Contracts.ts
src/contracts/exchanges/EngineAdapter.sol
src/contracts/exchanges/EthfinexAdapter.sol
src/contracts/exchanges/ExchangeAdapter.sol
src/contracts/exchanges/ExchangeAdapterInterface.sol
src/contracts/exchanges/KyberAdapter.sol
src/contracts/exchanges/MatchingMarketAdapter.sol
src/contracts/exchanges/MockAdapter.sol
src/contracts/exchanges/ZeroExV2Adapter.sol
src/contracts/fund/trading/Trading.sol
yarn.lock

Found a few bugs in the adapter logic, and ended up refactoring to make them less likely in the future.
@john-0x

Fix bugs in adaptors and refactor

---

src/contracts/fund/accounting/calls/getNativeToken.ts
src/contracts/fund/accounting/calls/performCalculations.ts

- Fix shareprice call & add getNativeToken

Fix shareprice & add getNativeToken

---

bin/melon.js
package.json
src/contracts/exchanges/transactions/makeOrderFromAccountOasisDex.ts
src/tests/integration/generalWalkthrough.test.ts
src/tests/system/playground-kyber.systest.ts
src/tests/system/playground-testing.systest.ts
src/tests/utils/toBeTrueWith.ts
src/utils/environment/constructEnvironment.ts
tsconfig.json

- Run system tests against devchain on travis
- Start with OasisDex trade on Kovan ... fails so with this call: isTokenPairWhitelisted (works in devchain 😕 )

System tests

---

deployments/configs/kovan-kyberPrice/005-our-old-oasisdex.json
deployments/configs/kovan-testing/000-init.json
deployments/configs/test/development-fresh.json
deployments/configs/test/kovan-fresh.json
deployments/kovan-testing.json
package.json
src/contracts/version/transactions/registerExchange.ts
src/contracts/version/transactions/updateExchange.ts
src/tests/system/playground-kyber.systest.ts
src/tests/system/playground-testing.systest.ts
src/tests/utils/testLogger.ts
src/utils/deploy/deploySystem.ts
src/utils/environment/getLogCurried.ts
src/utils/solidity/deployContract.ts
src/utils/solidity/transactionFactory.ts

Ladies and Gentlemen
With this pull request come two system tests that are able to setup a fund on Kovan that take an order from OasisDex. 
Here is one on the Kyber price feed track: https://kovan.etherscan.io/address/0xb6ae9739a78d3faa9c3c1e278234e28ffacca0c1
And here is one on our testing price feed track: https://kovan.etherscan.io/address/0x791c77f13b229e13ff2b6f86b3a7f4840ac4f3f6
Happy New Year

System tests - First v0.9 funds with trades on Kovan 🍾

---

deployments/configs/kovan-kyberPrice/006-takesCustody-fix.json
src/tests/system/playground-kyber.systest.ts
src/tests/utils/setupInvestedTestFund.ts
src/utils/deploy/deploySystem.ts

- Fix takesCustody in exchangeConfig
- Add makeOasisDexOrder, cancelOasisDexOrder and shutDownFund to playground-kyber tests

Fix exchange config

---

src/contracts/engine/calls/getAmguToken.ts
src/tests/system/playground-kyber.systest.ts
src/tests/system/playground-testing.systest.ts

Take 0x order on kyber pricefeed

---

src/contracts/dependencies/token/transactions/approve.ts

Document approve as JSDoc example

---

package.json
src/contracts/factory/calls/getFundDetails.ts
src/contracts/fund/hub/calls/getName.ts
yarn.lock

- Fix names in js (Related to #669)

Fix names js

---

README.md
deployments/configs/kovan-kyberPrice/007-fees.json
deployments/kovan-kyberPrice.json
package.json
src/contracts/exchanges/transactions/deployEthfinex.ts
src/contracts/version/Registry.sol
src/tests/utils/deployment.json
src/utils/deploy/deploySystem.ts
src/utils/deploy/deployThirdParty.ts

New deployment and npm publication with fee deployment

---

deployments/configs/kovan-kyberPrice/009-track-engine.json
package.json

v0.9.4 deployment 

---

src/tests/system/playground-oasisdex.systest.ts
src/tests/utils/setupInvestedTestFund.ts

Playground oasisdex

---

deployments/configs/kovan-kyberPrice/014-fixes-for-app.json
package.json
src/contracts/engine/Engine.sol
src/contracts/engine/transactions/deployEngine.ts
src/contracts/engine/transactions/sellAndBurnMln.test.ts
src/contracts/factory/FundFactory.sol
src/contracts/factory/calls/managersToHubs.test.ts
src/contracts/factory/transactions/beginSetup.ts
src/contracts/factory/transactions/deployFundFactory.ts
src/contracts/fund/participation/Participation.sol
src/contracts/version/Registry.sol
src/contracts/version/Version.i.sol
src/contracts/version/Version.sol
src/contracts/version/transactions/deployRegistry.ts
src/contracts/version/transactions/deployVersion.ts
src/tests/integration/fund0xTrading.test.ts
src/tests/integration/fundEthfinexTrading.test.ts
src/tests/integration/fundKyberTrading.test.ts
src/tests/integration/fundMaliciousToken.test.ts
src/tests/integration/fundQuoteAsset.test.ts
src/tests/integration/generalWalkthrough.test.ts
src/tests/integration/managementFee.test.ts
src/tests/integration/newFundTrading.test.ts
src/tests/integration/performanceFee.test.ts
src/tests/utils/setupInvestedTestFund.ts
src/utils/deploy/deployMockSystem.ts
src/utils/deploy/deploySystem.ts

- owner and deployer can be different
- remove `Version#securityShutDown()`
- get `priceSource`, `engine` and `mlnToken` dynamically rather than passing/checking values when creating a Fund

Changes for app

---

package.json
src/contracts/exchanges/third-party/kyber/calls/getExpectedRate.ts
src/contracts/exchanges/transactions/makeOrderFromAccountOasisDex.ts
src/contracts/fund/accounting/calls/getFundHoldings.ts
src/contracts/fund/trading/calls/exchangesToOpenMakeOrders.ts
src/contracts/fund/trading/calls/getFundOpenOrder.ts
src/contracts/fund/trading/calls/getOpenOrders.ts
src/contracts/fund/trading/transactions/makeOasisDexOrder.ts
src/contracts/fund/trading/transactions/takeOasisDexOrder.ts
src/contracts/fund/trading/transactions/takeOrderOnKyber.ts
src/index.ts
src/tests/integration/generalWalkthrough.test.ts
src/tests/integration/high-level/kyberTrading.test.ts
src/tests/utils/toBeTrueWith.ts
src/utils/constants/kyberEthAddress.ts
src/utils/environment/withDifferentAccount.ts

New deployment with changes needed in front-end.
Only TypeScript

Frontend trade integration v0.9.18

---

src/contracts/fund/accounting/Accounting.sol
src/tests/integration/managementFee.test.ts
src/tests/integration/performanceFee.test.ts

- Small bug in getFundHoldings function
- Uncomment lines in fees tests

Fees uncomment

---

src/contracts/fund/participation/calls/getRequest.ts
src/index.ts

Fix getRequest

---

src/contracts/factory/calls/getFundDetails.ts

- Fix https://github.com/melonproject/melon-lab/issues/281

Fix ranking

---

src/contracts/fund/participation/calls/hasExpiredRequest.ts
src/index.ts

- Add cancel request (https://github.com/melonproject/melon-lab/issues/292)

Add cancel request

---

src/contracts/fund/trading/calls/getAllowedExchanges.ts
src/index.ts

- Add call to get allowed exchanges

Add call to get allowed exchanges

---

deployments/configs/mainnet/001-test.json
deployments/kovan-kyberPrice.json
deployments/mainnet-kyberPrice.json

I did not make a new release but just updated the address

Update oasisdex exchange address

---

src/contracts/fund/participation/transactions/disableInvestment.ts

Add disableInvestment

---

src/contracts/fund/policies/calls/getPolicyInformation.ts

Apply keccak256 to function name and args

---

src/contracts/fund/trading/transactions/returnBatchToVault.ts

Add ts function for returnBatchToVault

---

CONTRIBUTING.md

Addresses issue https://github.com/melonproject/protocol/issues/836

Chore: update contribution doc with current practices

---

src/fund/participation/Participation.sol
tests/integration/managementFee.test.js

fix: should not deduct fee for manager if manager redeems his shares

---

deploy_in_testing.json

chore: add networkID to deploy_in_testing

---

.travis.yml
Makefile
deploy_in_testing.json

Use docker to compile in CI

---

src/exchanges/EthfinexAdapter.sol
src/fund/policies/risk-management/MaxConcentration.sol
tests/integration/fundRiskManagement.test.js
tests/mock/maxConcentration.test.js
tests/unit/exchanges/ethfinexOrder.test.js

fixes #821 
Rebase onto, and merge after #870

fix: MaxConcentration to evaluate post-trade concentration

---

CHANGELOG.md
src/factory/FundFactory.sol
src/fund/accounting/Accounting.sol
src/fund/hub/Hub.sol
src/fund/hub/Spoke.sol
src/fund/participation/Participation.sol
tests/contracts/MockFeeManager.sol
tests/contracts/MockHub.sol
tests/mock/trading.test.js
tests/mock/tradingCallbacks.test.js
tests/utils/deployMockSystem.js

Fix/pricefeed dynamically fetched from fund #846

---

src/exchanges/ZeroExV2Adapter.sol
src/exchanges/ZeroExV3Adapter.sol

fix: validate address inputs for cancelOrder in 0x-related adapters

---

src/engine/AmguConsumer.sol
tests/integration/amgu.test.js

fix: better amgu assertion

---

CONTRIBUTING.md

Resolves issue raised by @MrChico here: https://github.com/melonproject/protocol/pull/878

docs: updated solidity version in contribution guidelines
